version: "3"
services:
  tests:
    environment:
      ENV: test
    image: python_cicd
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
       - "./coverage:/app/coverage"

    command:  bash -c "sleep 5; chmod +x ./run_tests.sh; ./run_tests.sh"
